const LIST_RESTAURANTS = [
    { name: "Osteria del Pesce", address: "Via Verdi 18", image: "Immagini/ristoranti0.jpg" , description: "L'Osteria del pesce e' un ristorante in cui il culto del pesce viene curato nel dettaglio, una cucina semplice ma gustosa. Piatti abbondanti, ricchi di varieta' di pesce di qualita'." },
    { name: "Orient Express", address: "Via Pisa 7", image: "Immagini/ristoranti1.jpg", description: "Riscoprite il piacere di viaggiare in treno mentre attraversate le citta' piu' affascinanti d'Europa." },
    { name: "Pataclara", address: "Via Roma 53", image: "Immagini/ristoranti2.jpg", description: "Locale piccolo e tranquillo con cucina ricercata. Ottimo servizio al tavolo del cameriere e le sue proposte sui vini da abbinare. Scelta del menu' molto buona con un paio di pietanze fuori menu' assolutamente da assaggiare." },
    { name: "French Laundry", address: "Via Etna 21", image: "Immagini/ristoranti3.jpg", description: "Uno chef di alto livello, cibo fantastico, la pasticceria sublime e il servizio accurato. Un esperienza indimenticabile." },
    { name: "Pizza Pazza", address: "Via Empedocle 36", image: "Immagini/ristoranti4.jpg", description: "Personale gentile e disponibile, pizzaioli bravissimi, pizza buonissima e a buon prezzo. Ottima pizzeria !" },
    { name: "Ai Spaghettari", address: "Via Roma 6", image: "Immagini/ristoranti5.jpg", description: "Ristorante piacevole, personale cortese, cibo di ottima qualita', sia specialita' romane che menu' di pesce. Prezzi leggermente piu' cari di altri ristoranti ma ne vale davvero la pena !" },
    { name: "La Porta", address: "Via Bologna 10", image: "Immagini/ristoranti6.jpg", description: "Staff preparato e veloce, piatti fatti alla perfezione. Ristorante molto raffinato, le porzioni sono abbondanti e l' abbinamento con i vini e' perfetto. Da provare assolutamente !" },
    { name: "Morelli", address: "Via Milano 42", image: "Immagini/ristoranti7.jpg", description: "Bellissima e raffinata location che permette di scegliere sale raffinate ed eleganti o sale interne ed esterne stile bistrot raffinato. Qualita' dei piatti eccelsa, ampia e molto valida carta dei vini, personale simpatico e cordiale. Da consigliare !" },
];